### ISSUE TITLE
Capability question

### ISSUE THREAD

**Issue by kill4food** [bruno222/whatsapp-web-bot#1]
Very interesting project.

Is it possible to make a passive bot on whatsapp web that only downloads photos to a specific folder?

**Comment by bruno222** [comment]
Hi there. Sure, it is possible!

That's the best case for build a Bot using Whatsapp Web. You will NEVER EVER get banned by WhatsApp team, if you are going to just read messages (in your case, photos), I am 100% sure that you will not get banned.

You will have to change the code in order to:

1. Read all lastest messages.
2. Got new message? Good, click in this user ib other to open his chat.
3. Read all messages starting from your last read.
4. Found any photos? Good, save it!
5. Mark this chat as read internally, in your code.

If you need any help on this, let me know. My email is bruno222 atttttttt google mail dottttt com

**Comment by kill4food** [comment]
Thanks
