### ISSUE TITLE
auto execution of joke function

### ISSUE THREAD

**Issue by kihojoyo** [bruno222/whatsapp-web-bot#39]
whenever i send "@help"
after help reply 
it also send me a joke 

i am testing it on chrome , latest version 

i also have some questions 
1> instead of storing those jokes in an array 
can we do this with a file ? because if add some more jokes it will make script bulky (i was thinking about using it with my raspberry pi & if script get bulky it will take more time in processing & maybe crash ) 

2> can we upload story with this ? if not media then text stories ? 

3> It send group name in @help message i saw your reply in https://github.com/bruno222/whatsapp-web-bot/issues/38

can you add that code in your bot.js ?

**Comment by rzfzr** [comment]
1. I believe you can store them whenever you please, even get them from a online source, just drop them in a csv or spreadsheet and extract them from there.
2. If it's possible to do through the whatsapp web then yes.
3. I actually solved it differently than the issue linked, its a bit simpler, just extract from the "lastMsg"
`
		var lines = lastMsg.split('\n');
		lastName= lines[0].slice(0,-1)
		lines.splice(0,1);
		var m = lines.join('\n').trim().toLowerCase();`
Add this to after "let sendText" and use lastName instead of title, and you can use actualMsg aswell(it's lastMsg without the first line with "username: ")
Good luck

**Comment by kihojoyo** [comment]
i did some research & whatsapp doesn't allow posting story with web interface 
maybe in future they will support it for currently they dont...

& @rzfzr  thanks :)

**Comment by NelsonGaldeman** [comment]
Duplicate #30
